
```{r Setup}
remotes::install_github('rmcelreath/rethinking', upgrade=F)
```

## R code 3.1

```{r R code 3.1}
Pr_Positive_Vampire <- 0.95
Pr_Positive_Mortal <- 0.01
Pr_Vampire <- 0.001
Pr_Positive <- Pr_Positive_Vampire * Pr_Vampire +
               Pr_Positive_Mortal * ( 1 - Pr_Vampire )
( Pr_Vampire_Positive <- Pr_Positive_Vampire*Pr_Vampire / Pr_Positive )
```

## R code 3.2

```{r R code 3.2}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prob_p <- rep( 1 , 1000 )
prob_data <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- prob_data * prob_p
posterior <- posterior / sum(posterior)
```

## R code 3.3

```{r R code 3.3}
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
```

## R code 3.4

```{r R code 3.4}
plot( samples )
```

## R code 3.5

```{r R code 3.5}
library(rethinking)
dens( samples )
```

## R code 3.6

```{r R code 3.6}
# add up posterior probability where p < 0.5
sum( posterior[ p_grid < 0.5 ] )
```

## R code 3.7

```{r R code 3.7}
sum( samples < 0.5 ) / 1e4
```

## R code 3.8

```{r R code 3.8}
sum( samples > 0.5 & samples < 0.75 ) / 1e4
```

## R code 3.9

```{r R code 3.9}
quantile( samples , 0.8 )
```

## R code 3.10

```{r R code 3.10}
quantile( samples , c( 0.1 , 0.9 ) )
```

## R code 3.11

```{r R code 3.11}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep(1,1000)
likelihood <- dbinom( 3 , size=3 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
samples <- sample( p_grid , size=1e4 , replace=TRUE , prob=posterior )
```

## R code 3.12

```{r R code 3.12}
PI( samples , prob=0.5 )
```

## R code 3.13

```{r R code 3.13}
HPDI( samples , prob=0.5 )
```

## R code 3.14

```{r R code 3.14}
p_grid[ which.max(posterior) ]
```

## R code 3.15

```{r R code 3.15}
chainmode( samples , adj=0.01 )
```

## R code 3.16

```{r R code 3.16}
mean( samples )
median( samples )
```

## R code 3.17

```{r R code 3.17}
sum( posterior*abs( 0.5 - p_grid ) )
```

## R code 3.18

```{r R code 3.18}
loss <- sapply( p_grid , function(d) sum( posterior*abs( d - p_grid ) ) )
```

## R code 3.19

```{r R code 3.19}
p_grid[ which.min(loss) ]
```

## R code 3.20

```{r R code 3.20}
dbinom( 0:2 , size=2 , prob=0.7 )
```

## R code 3.21

```{r R code 3.21}
rbinom( 1 , size=2 , prob=0.7 )
```

## R code 3.22

```{r R code 3.22}
rbinom( 10 , size=2 , prob=0.7 )
```

## R code 3.23

```{r R code 3.23}
dummy_w <- rbinom( 1e5 , size=2 , prob=0.7 )
table(dummy_w)/1e5
```

## R code 3.24

```{r R code 3.24}
dummy_w <- rbinom( 1e5 , size=9 , prob=0.7 )
simplehist( dummy_w , xlab="dummy water count" )
```

## R code 3.25

```{r R code 3.25}
w <- rbinom( 1e4 , size=9 , prob=0.6 )
```

## R code 3.26

```{r R code 3.26}
w <- rbinom( 1e4 , size=9 , prob=samples )
```

## R code 3.27

```{r R code 3.27}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep( 1 , 1000 )
likelihood <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
set.seed(100)
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
```

## R code 3.28

```{r R code 3.28}
birth1 <- c(1,0,0,0,1,1,0,1,0,1,0,0,1,1,0,1,1,0,0,0,1,0,0,0,1,0,
0,0,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,
1,1,0,1,0,0,1,0,0,0,1,0,0,1,1,1,1,0,1,0,1,1,1,1,1,0,0,1,0,1,1,0,
1,0,1,1,1,0,1,1,1,1)
birth2 <- c(0,1,0,1,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,0,0,1,1,1,0,
1,1,1,0,1,1,1,0,1,0,0,1,1,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,0,1,1,0,1,1,0,1,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,1,1,
0,0,0,1,1,1,0,0,0,0)
```

## R code 3.29

```{r R code 3.29}
library(rethinking)
data(homeworkch3)
```

## R code 3.30

```{r R code 3.30}
sum(birth1) + sum(birth2)
```

